# Note: the Elixir build is unreliable via Travis CI - put this stuff back when/if they ever fix it
language: python
python:
  - '3.6'
before_install:
#  - wget -o $HOME/erlang.tar.bz2 https://s3.amazonaws.com/travis-otp-releases/binaries/ubuntu/14.04/x86_64/erlang-19.3-nonroot.tar.bz2
#  - mkdir -p ~/otp && tar -xf erlang-19.3-nonroot.tar.bz2 -C ~/otp/
#  - mkdir -p ~/.kerl
#  - echo '19.3,19.3' >> ~/.kerl/otp_builds
#  - echo '19.3 $HOME/otp/19.3' >> ~/.kerl/otp_builds
#  - source $HOME/otp/19.3/activate
#  - wget https://repo.hex.pm/builds/elixir/v1.6.4-otp-19.zip
#  - echo 'export ELIXIR_VERSION=1.6.4
#    export PATH=$HOME/.kiex/elixirs/elixir-1.6.4/bin:$PATH
#    export MIX_ARCHIVES=$HOME/.kiex/mix/elixir-1.6.4' > $HOME/.kiex/elixirs/elixir-1.6.4.env
#  - kiex install 1.6.4
#  - kiex use 1.6.4
#  - elixir --version
  - cd ./Artie/artie
#  - mix local
#  - mix local.rebar --force
#  - mix local.hex --force
#  - mix deps.get
#  - export ERLPORT_PYTHON=python3
  - pip install audiosegment
  - sudo add-apt-repository ppa:mc3man/trusty-media -y
  - sudo apt-get update
  - sudo apt-get install ffmpeg
  - sudo apt-get install sox
script:
  #- mix test --color --exclude remote:true --exclude manual:true
  - cd ../senses/dataproviders/tests
  - python -m unittest discover
